_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.10.15
            "5": 0.18.7
            "8":
                - 1
                - 5
            "12": 0.18.7
            "13": linux-x86_64
max_depth:
    value: 5
min_samples_leaf:
    value: 4
min_samples_split:
    value: 2
n_estimators:
    value: 200
