raw_path = '/blue/yonghui.wu/hoyinchan/Data/data2022raw/'
ct_names = ['KUMC']
pat_id_cols = ["CENTER_NAME", "PATID",  "ONSETS_ENCOUNTERID"]
race_mapping = \
{
    '01': 'American Indian or Alaska Native',
    'RACE:amer. indian': 'American Indian or Alaska Native',
    '02': 'Asian',
    'RACE:asian': 'Asian',
    '03': 'Black',
    'RACE:black': 'Black', 
    '04': 'Native Hawaiian',
    'RACE:asian/pac. isl': 'Native Hawaiian',
    'RACE:white': 'White',
    '05': 'White',
    '06': 'More Than One Race',
    '07': 'Other',
    'RACE:ot': 'Patient Refused',
    'OT': 'Patient Refused',
    'NI': 'No Information',
    'RACE:ni': 'No Information',
    'nan': 'No Information',
    'UN': 'Unknown',
    'RACE:unknown':  'Unknown'
}

nephrotoxical_drug_data = \
{'acetaminophen': {'class': 'Analgesics',
  'mechanism': ['Chronic interstitial nephritis']},
 'aspirin': {'class': 'Analgesics',
  'mechanism': ['Chronic interstitial nephritis']},
 'ibuprofen': {'class': 'Analgesics',
  'mechanism': ['Acute interstitial nephritis',
   'Altered intraglomerular hemodynamics',
   'Chronic interstitial nephritis',
   'Glomerulonephritis']},
 'naproxen': {'class': 'Analgesics',
  'mechanism': ['Acute interstitial nephritis',
   'Altered intraglomerular hemodynamics',
   'Chronic interstitial nephritis',
   'Glomerulonephritis']},
 'amitriptyline': {'class': 'Antidepressants/mood stabilizers',
  'mechanism': ['Rhabdomyolysis']},
 'doxepin': {'class': 'Antidepressants/mood stabilizers',
  'mechanism': ['Rhabdomyolysis']},
 'fluoxetine': {'class': 'Antidepressants/mood stabilizers',
  'mechanism': ['Rhabdomyolysis']},
 'lithium': {'class': 'Antidepressants/mood stabilizers',
  'mechanism': ['Chronic interstitial nephritis',
   'Glomerulonephritis',
   'Rhabdomyolysis']},
 'diphenhydramine': {'class': 'Antihistamines',
  'mechanism': ['Rhabdomyolysis']},
 'doxylamine': {'class': 'Antihistamines', 'mechanism': ['Rhabdomyolysis']},
 'acyclovir': {'class': 'Antimicrobials',
  'mechanism': ['Acute interstitial nephritis', 'Crystal nephropathy']},
 'gentamicin': {'class': 'Antimicrobials',
  'mechanism': ['Tubular cell toxicity']},
 'tobramycin': {'class': 'Antimicrobials',
  'mechanism': ['Tubular cell toxicity']},
 'amikacin': {'class': 'Antimicrobials',
  'mechanism': ['Tubular cell toxicity']},
 'amphotericin b': {'class': 'Antimicrobials',
  'mechanism': ['Tubular cell toxicity']},
 'amoxicillin': {'class': 'Antimicrobials',
  'mechanism': ['Acute interstitial nephritis', 'Glomerulonephritis']},
 'foscarnet': {'class': 'Antimicrobials',
  'mechanism': ['Crystal nephropathy', 'Tubular cell toxicity']},
 'ganciclovir': {'class': 'Antimicrobials',
  'mechanism': ['Crystal nephropathy']},
 'pentamidine': {'class': 'Antimicrobials',
  'mechanism': ['Tubular cell toxicity']},
 'ciprofloxacin': {'class': 'Antimicrobials',
  'mechanism': ['Acute interstitial nephritis', 'Crystal nephropathy']},
 'levofloxacin': {'class': 'Antimicrobials',
  'mechanism': ['Acute interstitial nephritis', 'Crystal nephropathy']},
 'moxifloxacin': {'class': 'Antimicrobials',
  'mechanism': ['Acute interstitial nephritis', 'Crystal nephropathy']},
 'rifampin': {'class': 'Antimicrobials',
  'mechanism': ['Acute interstitial nephritis']},
 'sulfamethoxazole': {'class': 'Antimicrobials',
  'mechanism': ['Acute interstitial nephritis', 'Crystal nephropathy']},
 'sulfisoxazole': {'class': 'Antimicrobials',
  'mechanism': ['Acute interstitial nephritis', 'Crystal nephropathy']},
 'vancomycin': {'class': 'Antimicrobials',
  'mechanism': ['Acute interstitial nephritis']},
 'adefovir': {'class': 'Antiretrovirals',
  'mechanism': ['Tubular cell toxicity']},
 'cidofovir': {'class': 'Antiretrovirals',
  'mechanism': ['Tubular cell toxicity']},
 'indinavir': {'class': 'Antiretrovirals',
  'mechanism': ['Acute interstitial nephritis', 'Crystal nephropathy']},
 'alprazolam': {'class': 'Benzodiazepines',
  'mechanism': ['Rhabdomyolysis']},
 'chlordiazepoxide': {'class': 'Benzodiazepines',
  'mechanism': ['Rhabdomyolysis']},
 'clonazepam': {'class': 'Benzodiazepines',
  'mechanism': ['Rhabdomyolysis']},
 'cyclosporine': {'class': 'Calcineurin inhibitors',
  'mechanism': ['Altered intraglomerular hemodynamics',
   'Chronic interstitial nephritis',
   'Thrombotic microangiopathy']},
 'tacrolimus': {'class': 'Calcineurin inhibitors',
  'mechanism': ['Altered intraglomerular hemodynamics']},
 'benazepril': {'class': 'Cardiovascular agents',
  'mechanism': ['Altered intraglomerular hemodynamics']},
 'captopril': {'class': 'Cardiovascular agents',
  'mechanism': ['Altered intraglomerular hemodynamics']},
 'enalapril': {'class': 'Cardiovascular agents',
  'mechanism': ['Altered intraglomerular hemodynamics']},
 'azilsartan': {'class': 'Cardiovascular agents',
  'mechanism': ['Altered intraglomerular hemodynamics']},
 'candesartan': {'class': 'Cardiovascular agents',
  'mechanism': ['Altered intraglomerular hemodynamics']},
 'irbesartan': {'class': 'Cardiovascular agents',
  'mechanism': ['Altered intraglomerular hemodynamics']},
 'clopidogrel': {'class': 'Cardiovascular agents',
  'mechanism': ['Thrombotic microangiopathy']},
 'ticlopidine': {'class': 'Cardiovascular agents',
  'mechanism': ['Thrombotic microangiopathy']},
 'atorvastatin': {'class': 'Cardiovascular agents',
  'mechanism': ['Rhabdomyolysis']},
 'fluvastatin': {'class': 'Cardiovascular agents',
  'mechanism': ['Rhabdomyolysis']},
 'lovastatin': {'class': 'Cardiovascular agents',
  'mechanism': ['Rhabdomyolysis']},
 'carmustine': {'class': 'Chemotherapeutics',
  'mechanism': ['Chronic interstitial nephritis']},
 'cisplatin': {'class': 'Chemotherapeutics',
  'mechanism': ['Chronic interstitial nephritis', 'Tubular cell toxicity']},
 'methotrexate': {'class': 'Chemotherapeutics',
  'mechanism': ['Crystal nephropathy']},
 'mitomycin-c': {'class': 'Chemotherapeutics',
  'mechanism': ['Thrombotic microangiopathy']},
 'triamterene': {'class': 'Diuretics', 'mechanism': ['Crystal nephropathy']},
 'cocaine': {'class': 'Drugs of abuse', 'mechanism': ['Rhabdomyolysis']},
 'heroin': {'class': 'Drugs of abuse', 'mechanism': ['Rhabdomyolysis']},
 'ketamine': {'class': 'Drugs of abuse', 'mechanism': ['Rhabdomyolysis']},
 'methadone': {'class': 'Drugs of abuse', 'mechanism': ['Rhabdomyolysis']},
 'methamphetamine': {'class': 'Drugs of abuse',
  'mechanism': ['Rhabdomyolysis']},
 'lansoprazole': {'class': 'Proton pump inhibitors',
  'mechanism': ['Acute interstitial nephritis']},
 'omeprazole': {'class': 'Proton pump inhibitors',
  'mechanism': ['Acute interstitial nephritis']},
 'pantoprazole': {'class': 'Proton pump inhibitors',
  'mechanism': ['Acute interstitial nephritis']},
}